apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ccm
  labels:
    app.kubernetes.io/name: ccm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ccm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ccm
    spec:
      hostNetwork: true # TODO for some reason the CCM cannot connect to the kube api server without being in the same network
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: cloud-controller-manager
      automountServiceAccountToken: true
      tolerations:
        - key: "node.cloudprovider.kubernetes.io/uninitialized"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: ccm
          image: ccm:latest
          imagePullPolicy: IfNotPresent
          command:
            - /ccm
          args:
            - --cloud-provider=salih-ccm
            - --leader-elect=false
            - --use-service-account-credentials=true
            - --cluster-name=ccm
          envFrom:
            - configMapRef:
                name: ccm-config
